services:
  db:
    image: postgres:16
    container_name: postgres-cs340
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata:
